/**
 * State Machine Definitions - myTrimmy-prep
 * Generated: 2026-01-14
 *
 * Client-safe state machine definitions.
 * These can be imported by both client and server components.
 *
 * IMPORTANT: This file contains NO server-only imports (like next/headers).
 * It's safe to use in 'use client' components.
 */



// ============================================================
// GENERATED BY MENTAL MODELS SDLC
// ============================================================
