/**
 * Config Generator
 *
 * Generates configuration files for the asset bundle:
 * - manifest.json (PWA)
 * - browserconfig.xml (Microsoft)
 * - README.md (documentation with HTML snippet)
 */

import type { ValidatedAssetBundleInput } from '@/lib/validation/asset-bundle';

/**
 * Generate PWA manifest.json content.
 */
export function generateManifest(config: ValidatedAssetBundleInput): string {
  const manifest = {
    name: config.appName,
    short_name: config.shortName || config.appName.slice(0, 12),
    description: config.description || '',
    start_url: config.startUrl,
    display: 'standalone',
    theme_color: config.themeColor,
    background_color: config.backgroundColor,
    icons: [
      {
        src: '/icon-192x192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/maskable-icon-192x192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'maskable',
      },
      {
        src: '/maskable-icon-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };

  return JSON.stringify(manifest, null, 2);
}

/**
 * Generate Microsoft browserconfig.xml content.
 */
export function generateBrowserconfig(config: ValidatedAssetBundleInput): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<browserconfig>
  <msapplication>
    <tile>
      <square150x150logo src="/mstile-150x150.png"/>
      <TileColor>${config.themeColor}</TileColor>
    </tile>
  </msapplication>
</browserconfig>`;
}

/**
 * Generate README.md with HTML snippet and file documentation.
 */
export function generateReadme(config: ValidatedAssetBundleInput): string {
  return `# ${config.appName} - App Assets

Generated by myTrimmy Asset Bundle Generator

## HTML Snippet

Add this to your \`<head>\` section:

\`\`\`html
<!-- Favicon -->
<link rel="icon" type="image/x-icon" href="/favicon.ico">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">

<!-- Apple Touch Icon -->
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">

<!-- PWA Manifest -->
<link rel="manifest" href="/manifest.json">

<!-- Theme Color -->
<meta name="theme-color" content="${config.themeColor}">
<meta name="msapplication-TileColor" content="${config.themeColor}">
<meta name="msapplication-config" content="/browserconfig.xml">

<!-- Open Graph -->
<meta property="og:image" content="/og-image.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">

<!-- Twitter Card -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="/twitter-card.png">
\`\`\`

## Included Files

### Favicons
- \`favicon.ico\` - Multi-resolution favicon (16x16, 32x32, 48x48)
- \`favicon-16x16.png\` - Small favicon
- \`favicon-32x32.png\` - Standard favicon
- \`favicon-48x48.png\` - Large favicon

### Apple Touch Icons
- \`apple-touch-icon.png\` (180x180) - Default iOS home screen
- \`apple-touch-icon-152x152.png\` - iPad
- \`apple-touch-icon-120x120.png\` - iPhone retina

### PWA Icons
- \`icon-192x192.png\` - Standard PWA icon
- \`icon-512x512.png\` - Large PWA icon / splash screen
- \`maskable-icon-192x192.png\` - Adaptive icon with safe zone
- \`maskable-icon-512x512.png\` - Large adaptive icon with safe zone

### Social Media
- \`og-image.png\` (1200x630) - Open Graph image (Facebook, LinkedIn, iMessage)
- \`twitter-card.png\` (1200x600) - Twitter card image

### Microsoft
- \`mstile-150x150.png\` - Windows Start tile

### Config Files
- \`manifest.json\` - PWA web app manifest
- \`browserconfig.xml\` - Microsoft browser configuration

## Installation

1. Copy all files to your \`public/\` directory (or equivalent static folder)
2. Add the HTML snippet above to your \`<head>\`
3. Update any paths if you placed files in a subdirectory

## Customization

If you need different background colors for social images, or custom theme colors, regenerate the bundle with updated settings.
`;
}
