// ============================================================
// API ROUTE HANDLERS - STATE MACHINE TRANSITIONS - myTrimmy-prep
// Generated: 2026-01-14
// ============================================================
//
// DYNAMIC ROUTE: /api/[entity]/[id]/transition
// Handles state machine transitions for entities with state machines.
//
// ============================================================

import { NextRequest } from "next/server";
import { getUser as getAuthUser } from "@/lib/supabase/server";
import {
  type ApiResponse,
  apiSuccess,
  apiError,
} from "@/types/api";
import {
  badRequest,
  unauthorized,
  notFound,
  internalError,
  apiErrorToStatus,
} from "@/types/errors";
import {
  logger,
  withSpan,
  httpErrorsTotal,
} from "@/lib/observability";

// ============================================================
// TYPES
// ============================================================

type TransitionableEntity = never;

interface RouteParams {
  params: Promise<{ entity: string; id: string }>;
}

interface TransitionRequest {
  transition: string;
}

// ============================================================
// ENTITY HANDLERS
// ============================================================


// ============================================================
// ROUTE HANDLERS
// ============================================================

/**
 * PATCH /api/[entity]/[id]/transition
 * Perform a state machine transition on an entity.
 *
 * Request body: { "transition": "transitionName" }
 * Response: Updated entity with new state
 */
export async function PATCH(
  request: NextRequest,
  { params }: RouteParams
): Promise<Response> {
  const { entity, id } = await params;

  if (!id) {
    const error = badRequest("Missing ID parameter");
    return Response.json(apiError(error), { status: apiErrorToStatus(error) });
  }

  switch (entity as TransitionableEntity) {
    default:
      const error = notFound(`Entity '${entity}' does not support transitions`);
      return Response.json(apiError(error), { status: apiErrorToStatus(error) });
  }
}

// ============================================================
// GENERATED BY MENTAL MODELS SDLC
// ============================================================
