// ============================================================
// API CONTRACTS - myTrimmy-prep
// Generated: 2026-01-14
// ============================================================
//
// API-FIRST DESIGN: Define request/response contracts BEFORE routes.
// These types are shared between client and server.
// Frontend uses these for type-safe API calls.
// Backend uses these to validate and respond.
//
// ============================================================

import type { Result } from "./errors.js";
import type { ApiError, ValidationError } from "./errors.js";

// ============================================================
// API RESPONSE WRAPPER
// ============================================================

/**
 * Standard API response envelope.
 * All API responses use this shape.
 */
export interface ApiResponse<T> {
  readonly success: boolean;
  readonly data?: T;
  readonly error?: {
    readonly type: string;
    readonly message: string;
    readonly details?: ValidationError[];
    readonly requestId?: string;
  };
  readonly meta?: {
    readonly total?: number;
    readonly page?: number;
    readonly limit?: number;
    readonly hasMore?: boolean;
  };
}

// Response constructors
export const apiSuccess = <T>(data: T, meta?: ApiResponse<T>["meta"]): ApiResponse<T> => ({
  success: true,
  data,
  meta,
});

export const apiError = (error: ApiError, requestId?: string): ApiResponse<never> => ({
  success: false,
  error: {
    type: error.type,
    message: "message" in error ? error.message : error.type,
    details: error.type === "bad_request" ? error.details : undefined,
    requestId,
  },
});

// ============================================================
// PAGINATION
// ============================================================

export interface PaginationParams {
  readonly page?: number;
  readonly limit?: number;
  readonly cursor?: string;
}

export interface PaginatedResponse<T> {
  readonly items: readonly T[];
  readonly total: number;
  readonly page: number;
  readonly limit: number;
  readonly hasMore: boolean;
  readonly nextCursor?: string;
}

// ============================================================
// ENTITY API CONTRACTS
// ============================================================


// ============================================================
// BATCH OPERATIONS
// ============================================================


// ============================================================
// ACTION ENDPOINTS (non-CRUD operations)
// ============================================================

// ============================================================
// TYPE-SAFE FETCH WRAPPER
// ============================================================

/**
 * Type-safe API client interface.
 * Implement this for your HTTP client (fetch, axios, etc.)
 */
// No entities defined - ApiClient type is a placeholder
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface ApiClient {}

// ============================================================
// WEBHOOK PAYLOADS (if using webhooks)
// ============================================================


// No entities defined - WebhookPayload type not generated
export type WebhookPayload = never;

// ============================================================
// GENERATED BY MENTAL MODELS SDLC
// ============================================================
