// ============================================================
// DOMAIN TYPES - myTrimmy-prep
// Generated: 2026-01-14
// ============================================================
//
// TYPE-FIRST DESIGN: These types are the contract.
// Implementation code MUST conform to these types.
// Do NOT modify types to fit implementation - fix the implementation.
//
// ============================================================

// ============================================================
// BRANDED ID TYPES
// ============================================================
// Branded types prevent accidentally passing wrong ID types

declare const __brand: unique symbol;
type Brand<T, B> = T & { [__brand]: B };


// ID constructors (use these, not raw strings)

// ============================================================
// CORE DOMAIN ENTITIES
// ============================================================


// ============================================================
// ENTITY RELATIONSHIPS
// ============================================================
/**
 * Relationship definitions from requirements:
 * - User has many Images (one-to-many)
- User has many Presets (one-to-many)
- User has many BatchJobs (one-to-many)
- BatchJob has many BatchImages (one-to-many)
- BatchJob belongs to Preset (optional, many-to-one)
- BatchImage belongs to Image (many-to-one)
- BatchImage belongs to BatchJob (many-to-one)
 */

// Imag many-to-one User
// Preset many-to-one User
// BatchJob many-to-one User
// BatchImag many-to-one BatchJob
// BatchJob many-to-one Preset
// BatchImage many-to-one Image
// BatchImage many-to-one BatchJob

// ============================================================
// VALIDATION CONSTRAINTS
// ============================================================


// ============================================================
// INPUT TYPES (for creating/updating)
// ============================================================
// These are what API endpoints accept - no IDs, no audit fields


// ============================================================
// FILTER/QUERY TYPES
// ============================================================


// ============================================================
// SENSITIVE DATA MARKERS
// ============================================================

// Fields that should NEVER be logged or exposed in errors
export const SENSITIVE_FIELDS = [
] as const;

export type SensitiveField = typeof SENSITIVE_FIELDS[number];

// ============================================================
// GENERATED BY MENTAL MODELS SDLC
// ============================================================
