// ============================================================
// API ROUTE HANDLERS - SINGLE RESOURCE ROUTES - myTrimmy-prep
// Generated: 2026-01-14
// ============================================================
//
// DYNAMIC ROUTE: /api/[entity]/[id]
// Handles get (GET), update (PATCH), delete (DELETE) for single resources.
//
// ============================================================

import { NextRequest } from "next/server";
import { getUser as getAuthUser } from "@/lib/supabase/server";
import {
  type ApiResponse,
  apiSuccess,
  apiError,
} from "@/types/api";
import {
  badRequest,
  unauthorized,
  forbidden,
  notFound,
  internalError,
  apiErrorToStatus,
} from "@/types/errors";
import {
  logger,
  withSpan,
  httpErrorsTotal,
} from "@/lib/observability";

// ============================================================
// TYPES
// ============================================================

// Support both singular and plural entity names in URL paths
type EntityName = never;

interface RouteParams {
  params: Promise<{ entity: string; id: string }>;
}

// ============================================================
// ENTITY HANDLERS
// ============================================================


// ============================================================
// ROUTE HANDLERS
// ============================================================

/**
 * GET /api/[entity]/[id]
 * Get a single entity by ID.
 */
export async function GET(
  request: NextRequest,
  { params }: RouteParams
): Promise<Response> {
  const { entity, id } = await params;

  if (!id) {
    const error = badRequest("Missing ID parameter");
    return Response.json(apiError(error), { status: apiErrorToStatus(error) });
  }

  switch (entity as EntityName) {
    default:
      const error = notFound(`Unknown entity: ${entity}`);
      return Response.json(apiError(error), { status: apiErrorToStatus(error) });
  }
}

/**
 * PATCH /api/[entity]/[id]
 * Update an entity by ID.
 */
export async function PATCH(
  request: NextRequest,
  { params }: RouteParams
): Promise<Response> {
  const { entity, id } = await params;

  if (!id) {
    const error = badRequest("Missing ID parameter");
    return Response.json(apiError(error), { status: apiErrorToStatus(error) });
  }

  switch (entity as EntityName) {
    default:
      const error = notFound(`Unknown entity: ${entity}`);
      return Response.json(apiError(error), { status: apiErrorToStatus(error) });
  }
}

/**
 * DELETE /api/[entity]/[id]
 * Delete an entity by ID.
 */
export async function DELETE(
  request: NextRequest,
  { params }: RouteParams
): Promise<Response> {
  const { entity, id } = await params;

  if (!id) {
    const error = badRequest("Missing ID parameter");
    return Response.json(apiError(error), { status: apiErrorToStatus(error) });
  }

  switch (entity as EntityName) {
    default:
      const error = notFound(`Unknown entity: ${entity}`);
      return Response.json(apiError(error), { status: apiErrorToStatus(error) });
  }
}

// ============================================================
// GENERATED BY MENTAL MODELS SDLC
// ============================================================
