-- ============================================================
-- STORAGE BUCKETS - myTrimmy-prep
-- Generated: 2026-01-14
-- ============================================================
--
-- Run with: supabase db push
-- Apply AFTER initial schema migration
--
-- ============================================================




-- ============================================================
-- HELPER FUNCTIONS FOR STORAGE
-- ============================================================

-- Get public URL for a storage object
-- Usage: SELECT get_public_url('bucket-name', 'path/to/file.jpg');
create or replace function get_public_url(bucket text, path text)
returns text as $$
  select concat(
    current_setting('app.settings.supabase_url', true),
    '/storage/v1/object/public/',
    bucket,
    '/',
    path
  );
$$ language sql stable;

-- ============================================================
-- GENERATED BY MENTAL MODELS SDLC
-- ============================================================
