-- ============================================================
-- SOFT DELETE MIGRATION - myTrimmy-prep
-- Generated: 2026-01-14
-- ============================================================
--
-- SUPABASE MIGRATION
-- Run with: supabase db push (dev) or supabase db push --linked (prod)
--
-- This migration adds soft delete support to all entities.
-- Soft delete preserves data for audit trails and recovery.
--
-- PATTERN: Instead of DELETE, set deleted_at timestamp.
-- All queries should filter WHERE deleted_at IS NULL by default.
-- Use *_active views for convenience.
--
-- ============================================================

-- ============================================================
-- SOFT DELETE COLUMNS
-- ============================================================
-- Add deleted_at and deleted_by columns to all entities


-- ============================================================
-- ACTIVE VIEWS
-- ============================================================
-- These views exclude soft-deleted rows for convenience.
-- Use these in application queries instead of raw tables.


-- ============================================================
-- SOFT DELETE FUNCTIONS
-- ============================================================
-- SECURITY DEFINER functions for soft delete operations.
-- These bypass RLS to ensure consistent behavior.


-- ============================================================
-- SOFT DELETE TRIGGER
-- ============================================================
-- Generic trigger function to handle soft delete via UPDATE
-- Use this when you want UPDATE ... SET deleted_at = NOW() to
-- automatically set deleted_by

CREATE OR REPLACE FUNCTION handle_soft_delete()
RETURNS TRIGGER AS $$
BEGIN
    -- Only trigger when deleted_at changes from NULL to a value
    IF OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL THEN
        -- Ensure deleted_by is set if not provided
        IF NEW.deleted_by IS NULL THEN
            NEW.deleted_by = auth.uid();
        END IF;
    END IF;

    -- If restoring (deleted_at set back to NULL), clear deleted_by
    IF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN
        NEW.deleted_by = NULL;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- RLS POLICY UPDATES
-- ============================================================
-- Update existing RLS policies to exclude soft-deleted rows.
-- IMPORTANT: Drop and recreate policies to add deleted_at filter.


-- ============================================================
-- ADMIN FUNCTIONS FOR DELETED RECORDS
-- ============================================================

-- View all soft-deleted records across tables (for admin dashboard)

-- Bulk hard delete old soft-deleted records
-- Returns count of deleted records per table
CREATE OR REPLACE FUNCTION cleanup_old_deleted_records(p_days_old INTEGER DEFAULT 90)
RETURNS TABLE(table_name TEXT, deleted_count BIGINT) AS $$
DECLARE
    v_cutoff_date TIMESTAMPTZ;
BEGIN
    v_cutoff_date := NOW() - (p_days_old || ' days')::INTERVAL;

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- SCHEDULED JOB FOR PERMANENT DELETION
-- ============================================================
-- IMPORTANT: Configure a scheduled job (pg_cron or external) to
-- periodically clean up old soft-deleted records.
--
-- Example pg_cron job (run monthly, delete records older than 90 days):
--
--   SELECT cron.schedule(
--       'cleanup-deleted-records',
--       '0 3 1 * *',  -- 3am on 1st of each month
--       $$SELECT cleanup_old_deleted_records(90)$$
--   );
--
-- For Supabase, use Edge Functions with a cron trigger or
-- external scheduler to call cleanup_old_deleted_records().
--
-- RETENTION POLICY:
-- - Default: 90 days retention for soft-deleted records
-- - Adjust based on compliance requirements (GDPR, CCPA, etc.)
-- - Consider longer retention for audit-critical data
-- ============================================================

-- ============================================================
-- GENERATED BY MENTAL MODELS SDLC
-- ============================================================
